To-Do-App/To-Do-App/Pages/AddToDo.cshtml.cs
/*
 * Razor page to add a new todo
 */


using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using To_Do_App.Model;
using To_Do_App.Services;

namespace To_Do_App.Pages
{

    public class AddToDoModel: PageModel
    {
        public ToDoModel ToDoItem = new();
        private ToDoService _service;

        [StringLength(60, MinimumLength = 3)]
        [Required]
        public string Name { get; set; } = string.Empty;
        public string Descrip { get; set; }

        public AddToDoModel(ToDoService service)
        {
            _service = service;
        }

        //Fill the field if user came from edit button
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id != null)
            {
                List<ToDoModel> items = _service.GetUncompleteToDos();

                ToDoItem = items.FirstOrDefault(m => m.Id == id);

                Name = ToDoItem.Name;
                Descrip = ToDoItem.Descrip;
            }

            return Page();
        }


        //Called on Submit to button to create a new todo or edit a todo
        public IActionResult OnPostSubmit(ToDoModel model)
        {
            if (model.Name == null)
            {
                return null;
            }

            if (model.Id == null)
            {
                model.Id = _service.GetUncompleteToDos().Count + 1;
                model.IsDone = false;
                _service.AddToDo(model);
            }
            else
            {
                List<ToDoModel> items = _service.GetUncompleteToDos();
                int index = items.FindIndex(m => m.Id == model.Id);
                _service.AddToDoAt(model, index);
            }

            return RedirectToPage("Home");

        }

    }
}

To-Do-App/To-Do-App/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace To_Do_App.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

To-Do-App/To-Do-App/Pages/Home.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using To_Do_App.Model;
using To_Do_App.Services;

namespace To_Do_App.Pages
{
    public class HomeModel : PageModel
    {
        private ToDoService _service;
        public List<ToDoModel> Items { get; set; }

        public HomeModel(ToDoService service)
        {
            _service = service;
        }

        //Called on page load
        public ActionResult OnGet()
        {
            Items = _service.GetUncompleteToDos();
            return Page();
        }

        //Called on Mark as Done button action
        public IActionResult OnPostSubmit(int id)
        {
            List<ToDoModel> items = _service.GetUncompleteToDos();
            ToDoModel model = items.Find(m => m.Id == id);

            Items = _service.MarkAsDone(model);
            return Page();
        }

    }
}

To-Do-App/To-Do-App/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace To_Do_App.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

To-Do-App/To-Do-App/Pages/AddToDo.cshtml
@page "{id:int?}"
@model To_Do_App.Pages.AddToDoModel
@{ ViewData["Title"] = "Add To Do"; }

<h1>Add a new ToDo</h1>

<body>
    <form method="post">
        <fieldset>
            <div>
                <label for="Name">Name:</label>
                <input type="text" name="Name" value="@Html.DisplayFor(modelItem => Model.Name)" />
            </div>
            <div>
                <label for="Descrip">Description:</label>
                <input type="text" name="Descrip" value="@Html.DisplayFor(modelItem => Model.Descrip)" />
            </div>
            <div>
                <label>&nbsp;</label>
                <td><input type="submit" value="Submit" asp-page-handler="Submit"/></td>
            </div>
        </fieldset>
    </form>
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

To-Do-App/To-Do-App/Pages/Home.cshtml
@page
@model To_Do_App.Pages.HomeModel
@{ ViewData["Title"] = "Home";
    Layout = null; }

<a asp-page="./AddToDo">Add ToDo</a>

<br />
<br />

<h1>ToDo List</h1>

@for (int i = 0; i < Model.Items.Count; i++)
{
    int index = i + 1;

<form method="post">

    <td>@index.  </td>
    <td>Name: </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Items.ElementAt(i).Name)<br />
    </td>
    <td>Description: </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Items.ElementAt(i).Descrip)<br />
    </td>

    <a asp-page="./AddToDo" asp-route-id="@Model.Items.ElementAt(i).Id">Edit</a>
    <td>
        <input type="hidden" name="id" value="@Model.Items.ElementAt(i).Id" />
        <input type="submit" value="Mark as Done" asp-page-handler="Submit" />
    </td>
    <br />
    <br />
</form>
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

To-Do-App/To-Do-App/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Home">ToDo App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Home">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>